### ISSUE TITLE
environment to get started

### ISSUE THREAD

**Issue by dschult** [dPys/nxbench#4]
I'm having trouble getting started with nx-bench. 
I naively started in a mamba environment, which cloned and installed many packages via pip successfully.
But when I try to run, it cant find the file `config/examples.yaml` even though it is there.

Should I be running in a docker environment for this to work?
Any hints on how to get it up and running?

**Comment by dPys** [comment]
Hi @dschult ,

Thanks for reaching out! It seems the issue may stem from the file path. If you'r running nxbench from the base of the package, then the correct path to the example config is `nxbench/configs/example.yaml` (not `nxbench/config/examples.yaml` -- i.e. it appears that you might have a typo with the extra "s"?). In other words, try running:
```
nxbench --config='nxbench/configs/example.yaml' benchmark run
```
The bottom line is that the path to `'example.yaml'` must exist. If the relative path fails, you could also try specifying the absolute path or checking the file's permissions.

When run verbosely without docker, your output should look something like this:
```
(base) bash-3.2$ nxbench -vv --config='/Users/derekpisner/Applications/nxbench/nxbench/configs/example.yaml' benchmark run
2024-12-08 03:40:34,934 - nxbench - INFO - Using config file: /Users/derekpisner/Applications/nxbench/nxbench/configs/example.yaml
INFO:nxbench:Using config file: /Users/derekpisner/Applications/nxbench/nxbench/configs/example.yaml
2024-12-08 03:40:34,935 - nxbench - DEBUG - Config file used for benchmark run: /Users/derekpisner/Applications/nxbench/nxbench/configs/example.yaml
DEBUG:nxbench:Config file used for benchmark run: /Users/derekpisner/Applications/nxbench/nxbench/configs/example.yaml
2024-12-08 03:40:34,935 - nxbench - DEBUG - Project root: /Users/derekpisner/Applications/nxbench
DEBUG:nxbench:Project root: /Users/derekpisner/Applications/nxbench
2024-12-08 03:40:34,935 - nxbench - DEBUG - Has .git: True
DEBUG:nxbench:Has .git: True
2024-12-08 03:40:34,936 - nxbench - DEBUG - Found .git directory. Using existing repository settings.
DEBUG:nxbench:Found .git directory. Using existing repository settings.
2024-12-08 03:40:34,936 - nxbench - DEBUG - Set benchmark_dir to: /Users/derekpisner/Applications/nxbench/nxbench/benchmarks
DEBUG:nxbench:Set benchmark_dir to: /Users/derekpisner/Applications/nxbench/nxbench/benchmarks
2024-12-08 03:40:34,937 - nxbench - DEBUG - Temporary asv.conf.json created at: /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp3zvwk5mf/asv.conf.json
DEBUG:nxbench:Temporary asv.conf.json created at: /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp3zvwk5mf/asv.conf.json
2024-12-08 03:40:34,938 - nxbench - DEBUG - Added --config /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp3zvwk5mf/asv.conf.json to ASV arguments.
DEBUG:nxbench:Added --config /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp3zvwk5mf/asv.conf.json to ASV arguments.
2024-12-08 03:40:34,938 - nxbench - DEBUG - Changed working directory to project root: /Users/derekpisner/Applications/nxbench
DEBUG:nxbench:Changed working directory to project root: /Users/derekpisner/Applications/nxbench
2024-12-08 03:40:34,938 - nxbench - DEBUG - Executing ASV command: /Users/derekpisner/anaconda3/bin/asv --config /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp3zvwk5mf/asv.conf.json run --quick --verbose --python=same
DEBUG:nxbench:Executing ASV command: /Users/derekpisner/anaconda3/bin/asv --config /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp3zvwk5mf/asv.conf.json run --quick --verbose --python=same
· No executable found for python /Users/derekpisner/anaconda3/bin/python3.10
· Running '/Users/derekpisner/anaconda3/bin/python -c import sys; print(str(sys.version_info[0]) + "." + str(sys.version_info[1]))'
  OUTPUT -------->
  3.10
· Discovering benchmarks
·· Running '/Users/derekpisner/anaconda3/lib/python3.10/site-packages/asv/benchmark.py discover /Users/derekpisner/Applications/nxbench/nxbench/benchmarks /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmpy2wp0x99/result.json' in existing-py_Users_derekpisner_anaconda3_bin_python
·· Running '/Users/derekpisner/anaconda3/bin/python /Users/derekpisner/anaconda3/lib/python3.10/site-packages/asv/benchmark.py discover /Users/derekpisner/Applications/nxbench/nxbench/benchmarks /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmpy2wp0x99/result.json'
· Running 108 total benchmarks (1 commits * 1 environments * 108 benchmarks)
[ 0.00%] ·· Benchmarking existing-py_Users_derekpisner_anaconda3_bin_python
[ 0.93%] ··· Setting up benchmark:109
[ 0.93%] ··· Running '/Users/derekpisner/anaconda3/lib/python3.10/site-packages/asv/benchmark.py setup_cache /Users/derekpisner/Applications/nxbench/nxbench/benchmarks benchmark.GraphBenchmark.track_number_of_isolates_08blocks_graphblas_1 {"cpu_affinity": null}' in existing-py_Users_derekpisner_anaconda3_bin_python
[ 0.93%] ··· Running '/Users/derekpisner/anaconda3/bin/python /Users/derekpisner/anaconda3/lib/python3.10/site-packages/asv/benchmark.py setup_cache /Users/derekpisner/Applications/nxbench/nxbench/benchmarks benchmark.GraphBenchmark.track_number_of_isolates_08blocks_graphblas_1 {"cpu_affinity": null}'                                                                                          ok
[ 0.93%] ··· benchmark.GraphBenchmark.track_number_of_isolates_08blocks_graphblas_1
[ 0.93%] ··· Running '/Users/derekpisner/anaconda3/lib/python3.10/site-packages/asv/benchmark.py run /Users/derekpisner/Applications/nxbench/nxbench/benchmarks benchmark.GraphBenchmark.track_number_of_isolates_08blocks_graphblas_1 {"number": 1, "repeat": 1, "warmup_time": 0, "rounds": 1} None /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp_pmjqz3x' in existing-py_Users_derekpisner_anaconda3_bin_python
[ 0.93%] ··· Running '/Users/derekpisner/anaconda3/bin/python /Users/derekpisner/anaconda3/lib/python3.10/site-packages/asv/benchmark.py run /Users/derekpisner/Applications/nxbench/nxbench/benchmarks benchmark.GraphBenchmark.track_number_of_isolates_08blocks_graphblas_1 {"number": 1, "repeat": 1, "warmup_time": 0, "rounds": 1} None /var/folders/b8/k4m1lr6949bb_mg68v4z52w00000gp/T/tmp_pmjqz3x' {"execution_time": 0.03744780598208308, "memory_used": 0.29155921936035156}
...
```

One other thing of note -- the package is now installable via pypi. So ensure you're using the latest version (`pip install -U nxbench`). Depending on your setup, running things using the docker-compose commands might also be worth trying, but for that you _do_ currently need a local clone of nxbench.

Let me know if this helps or share the exact command/error if the issue persists! 

Cheers,
@dPys 

p.s. the documentation is now also [live](https://dpys.github.io/nxbench/main/index.html), which might also be a good resource for the API docs.

**Comment by dschult** [comment]
Thanks for that example usage.  My results look like yours so long as I put in the full path to the config file (as you do). Using a relative path for the config file doesn't work however. 

There seem to be two parts to that. The argument checker looks for the file relative to where the command is run. And then the program looks for the file (probably relative to some other directory) and can't find it.

```
[~/NX/nxbench/nxbench/benchmarks]$ nxbench --config='../configs/example.yaml' benchmark run
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
· No executable found for python /Users/dschult/mambaforge/envs/nx-bench/bin/python3.11
· Discovering benchmarks
·· Error running /Users/dschult/mambaforge/envs/nx-bench/bin/python3.11 /Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv/benchmark.py discover /Users/dschult/NX/nxbench/nxbench/benchmarks /var/folders/bw/jgqy55tx79jb0dwhngb74_600000gr/T/tmp29lmsg6d/result.json (exit status 1)
   STDOUT -------->
 
   STDERR -------->
   Traceback (most recent call last):
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv/benchmark.py", line 80, in <module>
       main()
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv/benchmark.py", line 72, in main
       commands[mode](args)
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv_runner/discovery.py", line 310, in _discover
       list_benchmarks(benchmark_dir, fp)
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv_runner/discovery.py", line 278, in list_benchmarks
       for benchmark in disc_benchmarks(root):
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv_runner/discovery.py", line 144, in disc_benchmarks
       for module in disc_modules(root_name, ignore_import_errors=ignore_import_errors):
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv_runner/discovery.py", line 109, in disc_modules
       yield from disc_modules(name, ignore_import_errors)
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/site-packages/asv_runner/discovery.py", line 98, in disc_modules
       module = importlib.import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/dschult/mambaforge/envs/nx-bench/lib/python3.11/importlib/__init__.py", line 126, in import_module
       return _bootstrap._gcd_import(name[level:], package, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
     File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
     File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
     File "<frozen importlib._bootstrap_external>", line 940, in exec_module
     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
     File "/Users/dschult/NX/nxbench/nxbench/benchmarks/benchmark.py", line 101, in <module>
       @generate_benchmark_methods
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/dschult/NX/nxbench/nxbench/benchmarks/benchmark.py", line 39, in generate_benchmark_methods
       config = get_benchmark_config()
                ^^^^^^^^^^^^^^^^^^^^^^
     File "/Users/dschult/NX/nxbench/nxbench/benchmarks/utils.py", line 36, in get_benchmark_config
       raise FileNotFoundError(f"Config file not found: {config_file}")
   FileNotFoundError: Config file not found: nxbench/configs/example.yaml
```

The error message when relative file is based from another directory is:
```
 ~/NX/nxbench]$ nxbench --config='configs/example.yaml' benchmark run
Usage: nxbench [OPTIONS] COMMAND [ARGS]...
Try 'nxbench --help' for help.

Error: Invalid value for '--config': File 'configs/example.yaml' does not exist.
```

I can use the full path. So I'm good to go...    Thanks!

**Comment by dPys** [comment]
Closing this issue for now, but feel free to re-open if needed!
